# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # sync_code_signing(type: "appstore")
    build_app(
      configuration: "Release",
      clean: true
    )
    upload_to_testflight
    # slack(message: "Successfully distributed a new beta build")
  end
end
