# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :internal do
    # sync_code_signing(type: "appstore")
    build_app(
      configuration: "Release",
      clean: true,
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight
  end
end
