# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :beta do
    gradle(task: "clean")
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(track: 'beta')
    # slack(message: 'Successfully distributed a new beta build')
  end
end
