name: Build CLI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./cli
        run: yarn --frozen-lockfile
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Build library
        working-directory: ./cli
        run: yarn run build
