name: Build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'
    paths-ignore:
      - '.changeset/**'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build-cmake:
    name: Build CMake targets
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os:
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }
          - { os: windows-latest, shell: msys2 }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: clang
      CXX: clang++
      USE_CCACHE: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          release: false

      - name: Setup OpenGL on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xorg-dev
          sudo apt-get install freeglut3-dev
          sudo apt-get install libxi-dev
          sudo apt-get install libopengl0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CCache
        uses: eliasku/install-ccache-action@master

      - name: Setup CCache
        uses: eliasku/ccache-action@master
        with:
          key: ${{ runner.os }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build-native

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: ekc-linux
          path: tools/ekc/bin/linux

      - uses: actions/upload-artifact@v2
        if: runner.os == 'macOS'
        with:
          name: ekc-osx
          path: tools/ekc/bin/osx

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
          name: ekc-win32
          path: tools/ekc/bin/win32

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build-cmake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: ekc-osx
          path: tools/ekc/bin/osx

      - uses: actions/download-artifact@v2
        with:
          name: ekc-linux
          path: tools/ekc/bin/linux

      - uses: actions/download-artifact@v2
        with:
          name: ekc-win32
          path: tools/ekc/bin/win32

      - name: Intall Dependencies
        run: |
          yarn --version
          yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn run release
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
