name: Build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'
    paths-ignore:
      - '.changeset/**'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build-cmake:
    name: Build CMake targets
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os:
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }
          - { os: windows-latest, shell: msys2 }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: clang
      CXX: clang++
      USE_CCACHE: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          msystem: clang64
          release: false
          install: >-
            mingw-w64-clang-x86_64-winpthreads-git
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-gcc

      - name: Setup OpenGL (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CCache
        uses: eliasku/install-ccache-action@master

      - name: Setup CCache
        uses: eliasku/ccache-action@master
        with:
          key: ${{ runner.os }}

      - name: Fetch and test external tools
        run: |
          deno run -A ./tools/fetch.ts
          deno run -A ./tools/test.ts 

      - name: Build JS
        run: deno run -A build.ts

      - name: Build Native
        run: deno run -A native-build.ts

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: |
            tools/bin/
            external/
            modules/
            packages/
            plugins/
            import_map.json
            deno.jsonc
            CMakeLists.txt

      # llvm-profdata / llvm-cov
      - name: Install LLVM and Clang (Linux)
        uses: KyleMayes/install-llvm-action@v1
        if: runner.os == 'Linux'
        with:
          version: "10.0"

      - name: Coverage Native
        run: deno run -A native-coverage.ts

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build-cmake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: ${{ runner.os }}

      - name: Intall Dependencies
        run: |
          yarn --version
          yarn --frozen-lockfile
          yarn global add @changesets/cli

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn run release
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
