name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    name: Build CMake targets
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os:
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }
          - { os: windows-latest, shell: msys2 }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          release: false

      - name: Setup OpenGL on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xorg-dev
          sudo apt-get install freeglut3-dev
          sudo apt-get install libopengl0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Check installed versions
        run: |
          yarn --version
          cmake --version
          ninja --version
          clang++ --version
          node --version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build-native

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build
