name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    name: Build all CMake targets
    strategy:
      matrix:
        build-tyoe: [ Release ]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup OpenGL on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xorg-dev
          sudo apt-get install freeglut3-dev

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Check installed versions
        run: |
          yarn --version
          cmake --version
          ninja --version
          clang++ --version
          node --version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build ${{ matrix.build-tyoe }}
        run: |
          cmake . -B cmake-build-${BUILD_TYPE} -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build cmake-build-${{ matrix.build-tyoe }}
        env:
          BUILD_TYPE: ${{ matrix.build-tyoe }}

  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./cli
        run: yarn --frozen-lockfile

      - name: Build library
        working-directory: ./cli
        run: yarn run build
