name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    needs: build-cmake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Intall Dependencies
        run: |
          yarn --version
          yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build

      - uses: actions/download-artifact@v2
        with:
          name: ekc Linux

      - uses: actions/download-artifact@v2
        with:
          name: ekc macOS

      - name: Create Release Pull Request or Publish to NPM
        if: ${{ github.ref == 'refs/heads/master' }}
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn run release
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}